-- Inside init.lua
local modpath = minetest.get_modpath(minetest.get_current_modname())
dofile(modpath .. "/ingots.lua")
dofile(modpath .. "/commands.lua")
dofile(modpath .. "/weapons.lua")
dofile(modpath .."/mbfix.lua")
dofile(modpath .."/totem.lua")
dofile(modpath .."/seffects.lua")
dofile(modpath .."/status.lua")
dofile(modpath .. "/wands/init.lua")
