minetest.register_on_mods_loaded(function()
    for name, def in pairs(minetest.registered_items) do
        -- Check if it's a moreblocks shape generated by the circular saw
        if name:find("^moreblocks:") and (
           name:find("_stair") or 
           name:find("_slab") or 
           name:find("_panel") or 
           name:find("_micro") or
           name:find("_slope")
        ) then
            -- Copy the existing groups table so we don't destroy it
            local new_groups = table.copy(def.groups or {})
            new_groups.not_in_creative_inventory = 1
            
            -- Safely apply the update
            minetest.override_item(name, {
                groups = new_groups
            })
        end
    end
end)
